[AutoRun]
enabled=true
program=@CLAMAV_SCAN@ "%F"

[BitTorrent]
Session\DefaultSavePath=@SAVE_DIR@
Session\TempPath=@TEMP_DIR@
Session\TempPathEnabled=true

[LegalNotice]
Accepted=true

[Network]
PortForwardingEnabled=false

[Preferences]
General\Locale=en
WebUI\Username=guster
WebUI\LocalHostAuth=false